name: Deploy Test
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Kết nối ssh linux -> và pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        port: 22
        script: |
          cd /var/www/node/server
          git pull
          . $HOME/.nvm/nvm.sh
          nvm use
          npm install --omit=dev
          pm2 delete all
          pm2 start ./src/app.js
          curl -X POST -H "Content-Type: application/json" -H "Authorization:${{ secrets.DISCORD }}" -d '{"content":" @everyone Dự án node js đã deploy thành công link: https://testnode.giddyguy.io.vn "}' https://discord.com/channels/1193770923862532218/1193770923862532221/messages
